# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1E1E1E)
$foreground = rgb(F4F4F4)
$color0 = rgb(444444)
$color1 = rgb(494949)
$color2 = rgb(4D4D4D)
$color3 = rgb(5A5A5A)
$color4 = rgb(717171)
$color5 = rgb(A8A8A8)
$color6 = rgb(A8A8A8)
$color7 = rgb(E7E7E7)
$color8 = rgb(A2A2A2)
$color9 = rgb(616161)
$color10 = rgb(676767)
$color11 = rgb(777777)
$color12 = rgb(979797)
$color13 = rgb(E0E0E0)
$color14 = rgb(E0E0E0)
$color15 = rgb(E7E7E7)
