# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(131111)
$foreground = rgb(F5D6D4)
$color0 = rgb(3B3939)
$color1 = rgb(1B1211)
$color2 = rgb(38120F)
$color3 = rgb(543431)
$color4 = rgb(87231B)
$color5 = rgb(8D5652)
$color6 = rgb(AA6862)
$color7 = rgb(E8BCB9)
$color8 = rgb(A28481)
$color9 = rgb(241816)
$color10 = rgb(4B1814)
$color11 = rgb(704542)
$color12 = rgb(B32E24)
$color13 = rgb(BC736D)
$color14 = rgb(E28A83)
$color15 = rgb(E8BCB9)
