# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F4F4F4
background         #1E1E1E
cursor             #ADADAD

active_tab_foreground     #1E1E1E
active_tab_background     #F4F4F4
inactive_tab_foreground   #F4F4F4
inactive_tab_background   #1E1E1E

active_border_color   #F4F4F4
inactive_border_color #1E1E1E
bell_border_color     #494949

color0      #444444
color1		#494949
color2		#4D4D4D
color3		#5A5A5A
color4		#717171
color5		#A8A8A8
color6		#A8A8A8
color7		#E7E7E7
color8		#A2A2A2
color9		#616161
color10		#676767
color11		#777777
color12		#979797
color13		#E0E0E0
color14		#E0E0E0
color15		#E7E7E7
